// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZVXBWYy1Sixpuuw4yhHpvLlRyW3-xOLU',
    appId: '1:347297738621:web:4be6d2c1ff2afc505d2614',
    messagingSenderId: '347297738621',
    projectId: 'medvalut-auth',
    authDomain: 'medvalut-auth.firebaseapp.com',
    storageBucket: 'medvalut-auth.appspot.com',
    measurementId: 'G-7NZ2P0JRV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiyKIyYUbmOSlFV9bnVCBcAxeZAM-DvSE',
    appId: '1:347297738621:android:ee00e6064455d2ae5d2614',
    messagingSenderId: '347297738621',
    projectId: 'medvalut-auth',
    storageBucket: 'medvalut-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_Q208fiKYbkhn4chifacCi9f6lJjPE4g',
    appId: '1:347297738621:ios:a765b16236ccf02a5d2614',
    messagingSenderId: '347297738621',
    projectId: 'medvalut-auth',
    storageBucket: 'medvalut-auth.appspot.com',
    iosClientId: '347297738621-n7mb6u7rcj6f8va8jbcj1fp78tpg0n7l.apps.googleusercontent.com',
    iosBundleId: 'com.example.usalife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_Q208fiKYbkhn4chifacCi9f6lJjPE4g',
    appId: '1:347297738621:ios:daec479f26529d2a5d2614',
    messagingSenderId: '347297738621',
    projectId: 'medvalut-auth',
    storageBucket: 'medvalut-auth.appspot.com',
    iosClientId: '347297738621-c259l81eqiirj8rjn4o1tlbhcl3s8a7j.apps.googleusercontent.com',
    iosBundleId: 'com.example.usalife.RunnerTests',
  );
}
